### ISSUE TITLE
Jobs are getting sigterm

### ISSUE THREAD

**Issue by pkajaba** [samuelcolvin/arq#164]
When I am trying to execute code bellow, I am sometimes getting `SIGTERM` for those Workers which are running those jobs. 

Unfortunately, it's ~~not intermittent~~ intermittent, so it does not happen every time. Have you ever encountered this problem? 

```import asyncio
from arq import create_pool
from arq.connections import RedisSettings
from scipy import optimize
from arq.jobs import Job

def f1(z, *params):
    x, y = z
    a, b, c, d, e, f, g, h, i, j, k, l, scale = params
    return (a * x**2 + b * x * y + c * y**2 + d*x + e*y + f)

async def get_sigterm(ctx, i):
    print(f"starting {i}th iteration")
    params = (2, 3, 7, 8, 9, 10, 44, -1, 2, 26, 1, -2, 0.5)
    print(params)
    rranges = (slice(-300, 300, 0.25), slice(-300, 300, 0.25))
    optimize.brute(f1, rranges, args=params, full_output=True, finish=optimize.fmin, workers=-1)


async def main():
    redis = await create_pool(RedisSettings())
    for i in range(10):
        #await get_sigterm(None, i)
        job = await redis.enqueue_job('get_sigterm', i)

# WorkerSettings defines the settings to use when creating the work,
# it's used by the arq cli
class WorkerSettings:
    redis_settings = RedisSettings(conn_timeout=5000)
    functions = [get_sigterm]

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

Thanks a lot!

**Comment by samuelcolvin** [comment]
> Unfortunately, it's not intermittent, so it does not happen every time. 

You mean it **is** intermittent?

> I am sometimes getting sigterm for those Workers which are running those jobs

I don't know what you mean here? Are you seeing something in the log? If so what?

I will need more details to help.

**Comment by pkajaba** [comment]
Sorry, it is intermittent :-) 

There is nothing meaningful in logs. Just info about it received sigterm and this log from here: https://github.com/samuelcolvin/arq/blob/master/arq/worker.py#L454

**Comment by samuelcolvin** [comment]
> Just info about it received sigterm

What info?

**Comment by pkajaba** [comment]
```
15:22:54:  13.50s ← 4f982552509542b5ae7e5c803aaf5693:optimize ● <>
15:22:54: shutdown on SIGTERM ◆ 1 jobs complete ◆ 0 failed ◆ 0 retries ◆ 1 ongoing to cancel
Traceback (most recent call last):
  File "/home/pkajaba/Workspace/project/venv/bin/arq", line 10, in <module>
    sys.exit(cli())
  File "/home/pkajaba/Workspace/project/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pkajaba/Workspace/project/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pkajaba/Workspace/project/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pkajaba/Workspace/project/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pkajaba/Workspace/project/venv/lib/python3.7/site-packages/arq/cli.py", line 45, in cli
    run_worker(worker_settings, **kwargs)
  File "/home/pkajaba/Workspace/project/venv/lib/python3.7/site-packages/arq/worker.py", line 610, in run_worker
    worker.run()
  File "/home/pkajaba/Workspace/project/venv/lib/python3.7/site-packages/arq/worker.py", line 236, in run
    self.loop.run_until_complete(self.close())
  File "/home/pkajaba/.pyenv/versions/3.7.2/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
concurrent.futures._base.CancelledError
```

**Comment by samuelcolvin** [comment]
I would guess it's something to do with `optimize`.

Also i assume that `optimize` is a blocking (CPU intensive) call, you will therefore need to use [`ProcessPoolExecutor`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor) to take advantage of multiple processes.

Try that first and see if it fixes the problem or uncovers more details.

**Comment by pkajaba** [comment]
Thanks a lot! I will try to use `ProcessPoolExecutor`
