### ISSUE TITLE
Simple Usage example on mac with local redis throws TypeError

### ISSUE THREAD

**Issue by ar4hc** [samuelcolvin/arq#174]
i just tried arq on a mac, installed python using conda, and arq using pip, in that conda env.
the redis is running local, installed using brew.
(run of the mill mac setup...)

Just running the Simple Usage code gives:
```
 ./arq_bsp.py
Traceback (most recent call last):
  File "./arq_bsp.py", line 36, in <module>
    loop.run_until_complete(main())
  File "/usr/local/miniconda3/envs/web/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./arq_bsp.py", line 25, in main
    await redis.enqueue_job('download_content', url)
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/arq/connections.py", line 103, in enqueue_job
    with await self as conn:
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/aioredis/commands/__init__.py", line 133, in __await__
    conn = yield from self._pool_or_conn.acquire().__await__()
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/aioredis/pool.py", line 325, in acquire
    async with self._cond:
  File "/usr/local/miniconda3/envs/web/lib/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/usr/local/miniconda3/envs/web/lib/python3.8/site-packages/aioredis/locks.py", line 20, in acquire
    if not self._locked and all(w.cancelled() for w in self._waiters):
TypeError: 'NoneType' object is not iterable
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<RedisConnection._read_data() running at /usr/local/miniconda3/envs/web/lib/python3.8/site-packages/aioredis/connection.py:183> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f85389bf610>()]> cb=[Future.set_result()]>
```
Sooo.... the _waiters from aioredis are None for some reason ?
Why?
It's some pretty dumb setup issue but i have no idea how to debug further, 
and my google fu is bad today...

**Comment by ar4hc** [comment]
i think it this bug from [aioredis #726](https://github.com/aio-libs/aioredis/issues/726)
