### ISSUE TITLE
Redis TimeoutError when using multiple workers

### ISSUE THREAD

**Issue by waza-ari** [samuelcolvin/arq#265]
Hi there,

I am using your wonderful library for quite some time already. Right now I'm working on a tool which requires multiple workers to run, as roughly 900 jobs need to run in parallel. One task basically queues all the jobs (each job can take up to 20 seconds) and the 6 works work on them. 

What I now see is that some of the workers (currently all running locally on my PC using a local Redis instance) execute a few jobs, and then all of the sudden stop working with a Redis Timeout error. See the below logs from one of the workers:

```
(venv) ➜  asa-rule-checker arq worker.WorkerSettings
11:08:44: Starting worker for 6 functions: sync_firewalls_cmdb, parse_connected_routes, parse_static_routes, sync_all_routes, sync_firewall_routes, cron:sync_all_routes
11:08:44: redis_version=6.2.5 mem_usage=2.68M clients_connected=1 db_keys=1833
11:09:00:   1.01s → cron:sync_all_routes()
asarulechecker-worker 2021-10-04 11:09:00,247 INFO     route_sync.py:sync_all_routes Starting route sync for all firewalls
asarulechecker-worker 2021-10-04 11:09:00,341 INFO     route_sync.py:sync_all_routes Found 916 firewalls to process
11:09:00:   0.36s → 64cccb63b63949b090b6fcd74157930e:sync_firewall_routes(10, 8, 916)
asarulechecker-worker 2021-10-04 11:09:00,746 INFO     route_sync.py:sync_firewall_routes [8/916] Processing firewall xxx on management ip x
11:09:13:  13.04s ← 64cccb63b63949b090b6fcd74157930e:sync_firewall_routes ● 
11:09:13:  13.39s → 3d65075291cb4a1e904305e3c04429f5:sync_firewall_routes(21, 19, 916) delayed=13.39s
asarulechecker-worker 2021-10-04 11:09:13,806 INFO     route_sync.py:sync_firewall_routes [19/916] Processing firewall xxx on management ip x
11:09:19:   5.35s ← 3d65075291cb4a1e904305e3c04429f5:sync_firewall_routes ● 
11:09:19:  18.75s → 28921985985046a4b73609e34bf2d9af:sync_firewall_routes(22, 20, 916) delayed=18.75s
asarulechecker-worker 2021-10-04 11:09:19,168 INFO     route_sync.py:sync_firewall_routes [20/916] Processing firewall xxx on management ip x
asarulechecker-worker 2021-10-04 11:09:23,406 ERROR    route_sync.py:sync_firewall_routes Unable to connect to firewall x: Invalid credentials
11:09:23:   4.27s ← 28921985985046a4b73609e34bf2d9af:sync_firewall_routes ● 

[... a few are running in the meantime]

11:11:09: 129.36s → 27f0bfaff1f84c7c8aafe82992838a78:sync_firewall_routes(100, 98, 916) delayed=129.36s
asarulechecker-worker 2021-10-04 11:11:09,966 INFO     route_sync.py:sync_firewall_routes [98/916] Processing firewall xxx on management ip x
11:11:14:   4.34s ← 27f0bfaff1f84c7c8aafe82992838a78:sync_firewall_routes ● 
11:11:16: 135.93s ← cron:sync_all_routes ● 
Traceback (most recent call last):
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/bin/arq", line 8, in <module>
    sys.exit(cli())
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/arq/cli.py", line 48, in cli
    run_worker(worker_settings_, **kwargs)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/arq/worker.py", line 756, in run_worker
    worker.run()
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/arq/worker.py", line 256, in run
    self.loop.run_until_complete(self.main_task)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/arq/worker.py", line 308, in main
    await self._poll_iteration()
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/arq/worker.py", line 346, in _poll_iteration
    t.result()
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/arq/worker.py", line 419, in run_job
    v, job_try, _ = await asyncio.gather(*coros)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/aioredis/util.py", line 59, in wait_convert
    result = await fut
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/aioredis/pool.py", line 257, in _wait_execute
    conn = await self.acquire(command, args)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/aioredis/pool.py", line 324, in acquire
    await self._fill_free(override_min=True)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/aioredis/pool.py", line 398, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/aioredis/connection.py", line 111, in create_connection
    reader, writer = await asyncio.wait_for(open_connection(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
Task was destroyed but it is pending!
task: <Task pending name='Task-22' coro=<RedisConnection._read_data() running at /Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/aioredis/connection.py:186> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x105818f10>()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /Users/<user>/<company>/PythonProjects/asa-rule-checker/venv/lib/python3.8/site-packages/aioredis/connection.py:168]>
```

3 workers have failed with the error message above after running roughly 10-15 jobs, the other 3 workers are still working fine.

Arq version is:

```
arq -V
arq, version 0.22
```

**Comment by cmangla** [comment]
Did you try the solution in #231 : setting `conn_timeout`?

**Comment by JonasKs** [comment]
Closing for inactivity
