### ISSUE TITLE
TypeError: object NoneType can't be used in 'await' expression

### ISSUE THREAD

**Issue by michaeltoohig** [samuelcolvin/arq#304]
I'm having an odd problem where using `await` from an arq task causes the following error. However, using the same code directly in a FastAPI endpoint has no problem. I'm using latest release `0.22` and Python version `3.8`.

```
17:08:54: Starting worker for 4 functions: test_arq, test_arq_subtask, send_daily_push_notification, cron:app.tasks.utils.send_daily_push_notification
17:08:54: redis_version=6.2.5 mem_usage=855.38K clients_connected=1 db_keys=11
17:08:54:   0.50s → cron:app.tasks.utils.send_daily_push_notification()
17:08:55:   0.11s ! cron:app.tasks.utils.send_daily_push_notification failed, TypeError: object NoneType can't be used in 'await' expression
Traceback (most recent call last):
  File "/home/michael/.cache/pypoetry/virtualenvs/app-EOcAg-Cv-py3.8/lib/python3.8/site-packages/arq/worker.py", line 525, in run_job
    result = await task
  File "/home/michael/bilolok/backend/app/app/tasks/utils.py", line 30, in send_daily_push_notification
    push_notification = await crud_pn.create(PushNotificationSchemaIn(
  File "/home/michael/bilolok/backend/app/app/crud/base.py", line 38, in create
    await self._db_session.commit()
TypeError: object NoneType can't be used in 'await' expression
```

Here is the start of the task that the problem arises from. I'm calling the task via `cron` if that matters.

```python
async def send_daily_push_notification(ctx: dict):
    db = ctx["db"]
    crud_pn = CRUDPushNotification(db)
    crud_subscription = CRUDSubscription(db)
    data = dict(body="It's kava time; try finding a kava bar on Bilolok and check-in.")
    subs = await crud_subscription.get_multi()
    for sub in subs:
        push_notification = await crud_pn.create(PushNotificationSchemaIn(
            user_id=sub.user_id,
            device_id=sub.device_id,
            data=data,
        ))
        ...
```

The error arises from the `await crud_pn.create(...` which is below.

```python
class CRUDBase(Generic[TABLE, IN_SCHEMA, SCHEMA], metaclass=abc.ABCMeta):
    def __init__(self, db_session: AsyncSession, *args, **kwargs) -> None:
        self._db_session: AsyncSession = db_session

    @property
    @abc.abstractmethod
    def _table(self) -> Type[TABLE]:
        ...

    @property
    @abc.abstractmethod
    def _schema(self) -> Type[SCHEMA]:
        ...

    async def create(self, in_schema: IN_SCHEMA) -> SCHEMA:
        item = self._table(id=uuid4(), **in_schema.dict())
        self._db_session.add(item)
        await self._db_session.commit()
        return self._schema.from_orm(item)
```

Using the exact same code directly in a FastAPI endpoint raises no error. I can call `await self._db_session.commit()` but from arq the error arises. As if arq is not calling the task async but I'm not sure what is going on yet. I've called the sqlalchemy commit without `await` and it ran fine but I don't want to have to change my CRUD operations just for arq tasks.

Thank you for your insights.

**Comment by michaeltoohig** [comment]
```
async def startup(ctx):
    """
    Binds a connection set to the db object.
    """
    ctx["db_session"] = async_session



async def shutdown(ctx):
    """
    Pops the bind on the db object.
    """
    # ctx["db"].close()
```
