### ISSUE TITLE
Can't deploy ARQ workers on Dokku. redis connection error localhost:6379

### ISSUE THREAD

**Issue by RamonGiovane** [samuelcolvin/arq#361]
I've tested ARQ locally and it works just fine.

But when I try to deploy it using Dokku, it can't connect to Redis.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 709, in connect
    await self._connect()
  File "/usr/local/lib/python3.10/site-packages/redis/asyncio/connection.py", line 744, in _connect
    reader, writer = await asyncio.open_connection(
  File "/usr/local/lib/python3.10/asyncio/streams.py", line 47, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1063, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Cannot assign requested address
```
The funny thing is, I'm not using `127.0.0.1`. 

```python
from dynaconf import settings

class BaseWorker:
    """Defines the base settings of a worker."""

    functions = []
    allow_abort_jobs = True
    redis_settings = RedisSettings(host=settings.REDIS_HOST)

class FooReportWorker(BaseWorker):
    functions = [run_job]
    queue_name = 'foo_report_queue'

class BarReportWorker(BaseWorker):
    functions = [run_job]
    queue_name = 'bar_report_queue'
```

My Procfile contains something like:
```
web: make run
foo-report-worker: arq src.workers.foos_report_worker.FooReportWorker
bar-report-worker: arq src.workers.bar_report_worker.BarReportWorker
```
My env file contains:
```
REDIS_HOST='redis'
```

As I said, got any problems running it locally, but when I try to deploy it, it doesn't work. Seems like it is not even reading from the `redis_settings` attribute.

UPDATE: Just tested it out, I can pass any gibberish in the `host` attribute, no matter what, it always evaluate to `localhost` while initializing. 
While running it in my machine, it works, because localhost is what I need in this case.

Running from my local terminal
```
❯ arq src.workers.bar_report_worker.BarReportWorker
21:02:52: Starting worker for 1 functions: run_job
21:02:52: redis_version=7.0.5 mem_usage=1.32M clients_connected=1 db_keys=12
```

It only detects the wrong host parameter when something is scheduled, but it inits normally.
Same thing happens on Dokku, but it fails right in the initialization, since `127.0.0.1:6379` is not available there.

```
-----> Deploying bar-report-worker (count=1)
       Attempting pre-flight checks (bar-report-worker.1)
       Waiting for 10 seconds (bar-report-worker.1)
af7cb12712a5a3cca2d464d05c895d7566bc0e3252fe9bbd33d5fa0b0dc253a3
 !     App container failed to start (bar-report-worker.1)
=====> Start of xp-kye container output (bar-report-worker.1)
       19:58:13: redis connection error localhost:6379 ConnectionError Error connecting to localhost:6379. Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Cannot assign requested address., 5 retries remaining...
       19:58:14: redis connection error localhost:6379 ConnectionError Error connecting to localhost:6379. Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Cannot assign requested address., 4 retries remaining...
       19:58:15: redis connection error localhost:6379 ConnectionError Error connecting to localhost:6379. Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Cannot assign requested address., 3 retries remaining...
       19:58:16: redis connection error localhost:6379 ConnectionError Error connecting to localhost:6379. Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Cannot assign requested address., 2 retries remaining...
       19:58:17: redis connection error localhost:6379 ConnectionError Error connecting to localhost:6379. Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 6379), [Errno 99] Cannot assign requested address., 1 retries remaining...
       Traceback (most recent call last):
```

**Comment by RamonGiovane** [comment]
I think it's related to  https://github.com/samuelcolvin/arq/issues/305

**Comment by RamonGiovane** [comment]
Another test:

Env var:
```
REDIS_HOST='localhostsasdasd'
```

Worker settings
```python
class FooReportWorker(BaseWorker):
    functions = [run_job]
    queue_name = 'foo_report_queu
```
Running the command:

```bash
❯ arq -v foo.workers.foo_report_worker.FooReportWorker
{'host': 'localhostsasdasd', 'port': 6379, 'unix_socket_path': None, 'database': 0, 'username': None, 'password': None, 'ssl': False, 'ssl_keyfile': None, 'ssl_certfile': None, 'ssl_cert_reqs': 'required', 'ssl_ca_certs': None, 'ssl_ca_data': None, 'ssl_check_hostname': False, 'conn_timeout': 1, 'conn_retries': 5, 'conn_retry_delay': 1, 'sentinel': False, 'sentinel_master': 'mymaster'}
22:50:56: Starting worker for 1 functions: run_job
22:50:56: redis_version=7.0.5 mem_usage=1.32M clients_connected=1 db_keys=12
```

**Shouldn't this raise error since the host `localhostsasdasd` does not exist?**

I don't know, but I think that's what the guy from issue #305 was trying to say, it connects to `localhost` instead.

**Comment by RamonGiovane** [comment]
I could get it working, the error was in the `redis_settings`. It seems to not support inheritance for Worker Settings.

```pyhton
class BaseWorker:
    """Defines the base settings of a worker."""

    functions = []
    allow_abort_jobs = True
    redis_settings = RedisSettings(host=settings.REDIS_HOST)

class FooReportWorker(BaseWorker):
    functions = [run_job]
    queue_name = 'foo_report_queue'
    redis_settings = RedisSettings(host=settings.REDIS_HOST)

class BarReportWorker(BaseWorker):
    functions = [run_job]
    queue_name = 'bar_report_queue'
    redis_settings = RedisSettings(host=settings.REDIS_HOST)
```
Less elegant, but it works!

For those who may struggle to integrate it with  Dokku, just an advice: you need to access `dokku redis:info` and use the address available there as `host`. It's not `localhost`, neither `redis`.
