### ISSUE TITLE
CancelledError allowing drain to drain

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/arq#46]
tasks should not take 20seconds to finish, I suspect something has gone wrong.

Also loads of  `20 pending tasks, waiting for one to finish`, should be a way to suppress them

```
17:35:12 WorkProcess: drain waiting 20.0s for 19 tasks to finish
17:35:32 WorkProcess: dft  ran in 43.929s ← Sender.send ● 
Exception in callback Drain._job_callback(<Task cancell...orker.py:154>>)
handle: <Handle Drain._job_callback(<Task cancell...orker.py:154>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/samuel/code/arq/arq/drain.py", line 154, in _job_callback
    task_exception = task.exception()
concurrent.futures._base.CancelledError
Exception in callback Drain._job_callback(<Task cancell...orker.py:154>>)
handle: <Handle Drain._job_callback(<Task cancell...orker.py:154>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/samuel/code/arq/arq/drain.py", line 154, in _job_callback
    task_exception = task.exception()
concurrent.futures._base.CancelledError
Exception in callback Drain._job_callback(<Task cancell...orker.py:154>>)
handle: <Handle Drain._job_callback(<Task cancell...orker.py:154>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/home/samuel/code/arq/arq/drain.py", line 154, in _job_callback
    task_exception = task.exception()
concurrent.futures._base.CancelledError
```

**Comment by samuelcolvin** [comment]
also `Drain should raise an error on `__aexit__` if tasks had to be cancelled

**Comment by samuelcolvin** [comment]
The slow end was caused by `wait()` being slow and is now fixed.

Should still raise an error on `__aexit__`
