### ISSUE TITLE
Is it possible to be alive after redis restart?

### ISSUE THREAD

**Issue by kalloc** [samuelcolvin/arq#9]
```
20:16:07 WorkProcess: dft  ran in  1.169s ← Downloader.download_content ● 88346
20:16:34 WorkProcess: shutting down worker, waiting for 6 jobs to finish
20:16:34 WorkProcess: shutting down worker after 460.835s ◆ 6 jobs done ◆ 0 failed ◆ 0 timed out
20:16:34 WorkProcess: Worker exiting after an unhandled error: CancelledError
Traceback (most recent call last):
  File "/…/venv/lib/python3.5/site-packages/arq/worker.py", line 353, in start_worker
    worker.run_until_complete()
  File "/…/venv/lib/python3.5/site-packages/arq/worker.py", line 130, in run_until_complete
    self.loop.run_until_complete(self.run())
  File "/…/.pyenv/versions/3.5.2/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/…/.pyenv/versions/3.5.2/lib/python3.5/asyncio/futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError
20:16:34 MainProcess: worker process 17776 exited badly with exit code 1
```

**Comment by samuelcolvin** [comment]
It would be possible in theory, however I previously decided that the main process should not attempt to restart worker process if it dies.

Instead whatever scheduler or supervisor you're using for the main process should restart that.

For example I'm running arq with docker, in compose I have

```yaml
  worker:
    build: .
    entrypoint:
    - arq
    - path/to/worker.py
    restart: always
    depends_on:
    - redis
```

So docker is responsible for restarting the container, with that I get all the good of docker's restart logic: `docker ps` shows how long the worker has been running for and could abandon restarts if it never works.

If you really want `arq` to restart itself and aren't using docker or another scheduler you could create a very short bash script to do so.

**Comment by kalloc** [comment]
Ok, I understand you.
So, i will use supervisord 
thank you

**Comment by samuelcolvin** [comment]
great, supervisord's restart logic will be a lot more sophisticated than mine would be :-)

**Comment by samuelcolvin** [comment]
Reopening this issue since I think arq should be able restart the worker after it crashes.

Reasons:
* can implement better logic on restarts and delays - currently docker just restarts the the container as fast as possible and causes a log storm.
* should employ same logic as #70
